version: '3.9'
services:
  postgres:
    image: 'postgres:13'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: perfums_db
    volumes:
      - ./init:/docker-entrypoint-initdb.d